server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dishembitov/finflow-microservices-configurations.git
          search-paths: configuration
          default-label: main
